/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2018-11-06 23:07:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import classeConexao.*;
import java.sql.*;

public final class insereOcorrencia_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

   	Conexao conexao = new Conexao();
   	int registros = 0;
	// Comando SQL, que ira realizar o Insert no banco de dados.
    String query =	"INSERT INTO Ocorrencia (acontecimento, hora_data_registro, _status, nivel_ocorrencia," + 
    		" data_acontecimento, hora_do_termino, hora_de_inicio, id_area, id_func) " + 
    				"VALUES ('";
    				if(!request.getParameter("acontecimento").equals("InvasÃ£o"))
   						query += request.getParameter("acontecimento") + "','";
    				else{
    					query += "Invasão','";
    				}
   					query += request.getParameter("hora_data_registro") + "','" +
   					request.getParameter("_status") + "','";
   					if(request.getParameter("nivel_ocorrencia").equals("Alto") || request.getParameter("nivel_ocorrencia").equals("Baixo")){
   		   				query += request.getParameter("nivel_ocorrencia") + "','";
   					}else{
   						query += "Médio','";
   					}
   		   			query += request.getParameter("data_acontecimento") + "',";
   		   			if(request.getParameter("hora_do_termino").equals("null")){
   	   					query += request.getParameter("hora_do_termino") + ",'"; 
   		   			}else{
   		   				query += "'" + request.getParameter("hora_do_termino") + "','";
   		   			}
   	   				query += request.getParameter("hora_de_inicio") + "','" +
   	   		   		request.getParameter("id_area") + "','" +
   					request.getParameter("id_func") + "')";
        try{
        	//Executando o comando (query) SQL.
        	out.println(query);
        	conexao.ponte.executeUpdate(query);
        }
        catch(Exception erro){
             System.err.print("Erro ao Gravar "+erro);
        }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
